JNU-econovation/jnu-wiki-fe

src/components/common/layout/Sidebar.jsx

feat: Add sidebar2

---

.eslintrc.cjs
src/App.jsx
src/components/common/layout/Button.jsx
src/components/common/layout/Header.jsx
src/components/common/layout/Sidebar.jsx
src/pages/Join.jsx
src/pages/Login.jsx

- 사이드바 그림자 수정
- 헤더 각 컴포넌트 클릭시 라우터 추가(추후 로그인 상태에 따라 수정 필요)
- 로그인, 회원가입 페이지에 사이드바와 헤더만 추가

fix header route

---

src/components/common/ResisterCompo/AlertMessage.jsx
src/components/common/ResisterCompo/Box.jsx
src/components/common/ResisterCompo/Button.jsx
src/components/common/ResisterCompo/Container.jsx
src/components/common/ResisterCompo/DoubleCheck.jsx
src/components/common/ResisterCompo/Input.jsx
src/components/common/ResisterCompo/InputGroup.jsx
src/components/common/ResisterCompo/Label.jsx
src/components/common/ResisterCompo/Question.jsx
src/components/common/ResisterCompo/Title.jsx
src/hooks/useInput.jsx
src/services/regex.jsx

feat:Login-components

---

src/App.jsx
src/components/common/Resister/Box.jsx
src/components/common/admin/AdminBox.jsx
src/components/common/admin/Contain.jsx
src/components/common/admin/Request.jsx
src/components/common/admin/RequestContain.jsx
src/components/common/admin/RequestContainerBox.jsx
src/components/common/admin/TestData.jsx
src/components/common/admin/TitleBox.jsx
src/components/common/form/AdminForm.jsx
src/components/common/form/LoginForm.jsx
src/components/common/layout/Sidebar.jsx
src/components/common/layout/SidebarList.jsx
src/pages/Admin.jsx

admin 처음 들어왔을때 페이지 api로 데이터 받는것 빼고 구현했습니다.(테스트 데이터는 따로 넣어줌)
이거 머지하고 풀 받아주세요!

feat: Add admin

---

src/components/common/Document/CreateDocument.jsx
src/components/common/Document/DocumentInputGroup.jsx
src/components/common/document/CreateDocument.jsx
src/components/common/document/Document.jsx
src/components/common/document/DocumentHeading.jsx
src/components/common/document/DocumentTime.jsx
src/components/common/layout/Map.jsx
src/components/common/layout/Sidebar.jsx
src/hooks/useInput.jsx
src/store/addressReducer.js

- get 요청으로 문서 데이터 불러오기(일단은 testData 사용)
- 문서 열면 해당 장소에 마커가 찍힘

feat: open document and set marker

---

src/components/common/search/DocsItem.jsx
src/components/common/search/DocsList.jsx
src/services/document.jsx

feat: add infinite scroll

---

package-lock.json
package.json
src/components/common/document/Document.jsx
src/services/document.jsx
src/services/index.jsx

feat: add toastify

---

src/components/common/document/Document.jsx
src/services/document.jsx

fix: request basic info modify 

---

src/components/common/Input/InputGroup.jsx
src/components/common/Resister/Button.jsx
src/components/common/Resister/Container.jsx
src/components/common/Resister/DoubleCheck.jsx
src/components/common/form/LoginForm.jsx
src/components/common/form/ResisterForm.jsx
src/pages/BasicInfoEditReq.jsx

- 엔터 시 로그인 할 수 있는 기능 추가
- 저장 시 prettier, eslint 적용되게 수정

feat:login enter

---

src/components/common/Resister/Box.jsx
src/components/common/Resister/DoubleCheck.jsx
src/components/common/form/LoginForm.jsx
src/components/common/form/MyInfoEditForm.jsx
src/components/common/form/MypageForm.jsx
src/components/common/form/ResisterForm.jsx
src/components/common/mypage/MyBtn.jsx
src/pages/Admin.jsx
src/pages/MyPage.jsx
src/utils/handlePasswordVisible.jsx

feat:비밀번호 눈 추가

---

src/components/common/admin/AdminBox.jsx
src/components/common/admin/EditInfo.jsx
src/components/common/admin/RequestContain.jsx
src/components/common/admin/RequestContainerBox.jsx
src/components/common/admin/TitleBox.jsx
src/services/user.jsx

fix:관리자페이지 Error

---

src/components/common/admin/AdminBox.jsx
src/components/common/admin/Request.jsx
src/components/common/admin/RequestContain.jsx
src/components/common/admin/RequestContainerBox.jsx
src/components/common/layout/SidebarList.jsx
src/services/user.jsx

- 관리자페이지 무한스크롤 구현
- 추후에 애니메이션 , 새 요청 없을때 에러처리 백엔드 통일 후 구현
- 문서 없을떄 서버에서 에러메세지 보내니깐 문서 있어도 무한스크롤에서 다음 페이지의 문서가 없다고 떠서 그냥 에러메세지 안주는게 좋을 듯

feat:infiniteScroll

---

src/components/common/document/Document.jsx
src/components/common/document/DocumentHeading.jsx
src/components/common/document/DocumentTime.jsx
src/components/common/layout/Header.jsx

feat: display markdown and change icon name

---

src/components/common/document/DocsList.jsx
src/components/common/document/Document.jsx
src/components/common/document/ScrapBtn.jsx

- 문서 상세 조회 시 스크랩 기능 추가 (close #76)
- 문서 목록 조회 시 delete api 요청 안되는 문제 해결

feat: 문서 상세 조회 스크랩 기능 추가

---

src/components/common/document/CreateDocument.jsx
src/components/common/document/Document.jsx
src/components/common/document/ToggleBtn.jsx
src/pages/DocumentListPage.jsx
src/pages/DocumentPage.jsx

- 토글 버튼으로 문서 접는 기능 추가 (close #79 )

feat: 문서 접는 기능 추가

---

src/components/common/admin/AdminBox.jsx
src/components/common/mypage/MypageScrap.jsx
src/components/common/mypage/MypageStyle.js
src/components/common/mypage/ScrapDocs.jsx
src/components/common/mypage/ScrapList.jsx
src/pages/Scrap.jsx
src/services/mypage.jsx

feat: 마이페이지 스크랩 기능 추가

---

src/components/common/admin/AdminBox.jsx
src/components/common/mypage/MypageScrap.jsx
src/components/common/mypage/ScrapDocs.jsx
src/components/common/mypage/ScrapList.jsx

- 로그인 시, 구글 소셜 로그인 기능 추가
( 서버에서 lat,lng 아직 안보내줘서 디테일 페이지 가면 에러생겨요,,ㅜㅜ)
- 무한스크롤도 약간 수정

fix:mypagescrap

---

src/components/common/Resister/Container.jsx
src/components/common/admin/AdminBox.jsx
src/components/common/admin/Contain.jsx
src/components/common/admin/RequestContain.jsx
src/components/common/admin/RequestContainerBox.jsx
src/components/common/form/AdminForm.jsx
src/components/common/layout/SidebarList.jsx
src/pages/BasicInfoEditReq.jsx
src/pages/NewDocsReq.jsx
src/services/index.jsx
src/styles/globalStyle.jsx

- 로그인, 마이페이지, 회원가입 컨테이너 가운데정렬
- 나한테는 가운데로 오는데 너꺼 화면에서도 한번 확인해주라,,!
- 스크롤바, 어드민 페이지도 수정

fix:login/join container center

---

src/components/common/admin/AdminBox.jsx
src/components/common/admin/RequestContain.jsx
src/components/common/admin/RequestContainerBox.jsx
src/components/common/admin/TitleBox.jsx
src/pages/BasicInfoEditReq.jsx
src/pages/NewDocsReq.jsx

- 어드민 새로 고친 서버에서 이상하게 되길래 로딩이랑 에러처리 수정했습니다

fix:admin_loading

---

src/components/common/layout/Header.jsx
src/components/search/SearchBar.jsx

- 검색바 넓이 변경
- 회원가입, 로그인 버튼 위치 수정

fix: 헤더 아이콘 위치 수정

---

src/components/common/layout/Header.jsx
src/components/search/SearchBar.jsx
src/components/search/SearchItem.jsx

- 회원가입, 로그인 버튼 위치 변경
- 검색바 크기 변경
- 검색 아이템 커서 추가

fix: 헤더 넓이 변경

---

src/components/common/admin/RequestContain.jsx
src/components/common/admin/TitleBox.jsx
src/components/common/layout/Header.jsx
src/components/search/SearchBar.jsx

feat: 어드민 reload

---

src/components/common/layout/Header.jsx

fix: ButtonGroup 수정

---

src/pages/DocumentPage.jsx

- documentPage.jsx 위도 경도 받는 부분에서 mypage scrap은 docsrequestlocation 이라 이것도 받아줄 수 있게 수정했습니다

fix:documentPage_lnglat

---

src/App.jsx
src/components/Map/MapContainer.jsx
src/components/common/Resister/Container.jsx
src/components/common/admin/AdminBox.jsx
src/components/common/admin/Contain.jsx
src/components/common/admin/RequestContain.jsx
src/components/common/admin/RequestContainerBox.jsx
src/components/common/document/CreateDocument.jsx
src/components/common/layout/MainLayout.jsx
src/components/common/layout/MypageSidebar.jsx
src/components/common/layout/Sidebar.jsx
src/components/common/layout/SidebarList.jsx
src/components/common/mypage/MypageScrap.jsx
src/components/common/mypage/MypageScrapDetail.jsx
src/components/common/mypage/MypageStyle.js
src/components/common/mypage/ScrapList.jsx
src/pages/BasicInfoEditReq.jsx
src/pages/MypageScrapDetailPage.jsx
src/pages/NewDocsReq.jsx
src/pages/Scrap.jsx
src/routes.js

사이드바 width 너무 큰거같아서 줄였는데 지도랑 docs container left 15rem 주면 될거같아..! 혹시 이상해진거 있으면 말해줘!!

fix: 사이드바 width

---

src/components/common/layout/Header.jsx
src/components/common/layout/Sidebar.jsx
src/components/document/CreateDocument.jsx
src/components/document/Document.jsx
src/components/document/DocumentHeading.jsx
src/components/document/DocumentTime.jsx
src/components/document/InfoGroup.jsx
src/components/document/ScrapBtn.jsx
src/components/document/ToggleBtn.jsx

feat: 레이아웃 변경

---

src/components/mypage/MypageScrapDetail.jsx

fix: 스크랩 문서 레이아웃 변경

---

src/components/common/layout/Button.jsx
src/components/common/layout/Header.jsx

- 버튼 radius 수정 (웹 전체적인 통일성을 위해)
- 로그인 시 유저의 닉네임 띄우기
- Header.jsx 코드 리팩토링 (return 문에서 로직은 함수로)

fix: 헤더 UI 수정, 닉네임 보이기

---

src/components/common/layout/Header.jsx
src/components/document/CreateDocument.jsx

- 로그아웃 상태일 때
- 문서 생성 요청 비활성화
- 멤버 쿼리 비활성화

fix: 멤버 쿼리, 문서생성 수정

---

src/components/common/Input/InputGroup.jsx
src/components/common/form/LoginForm.jsx
src/components/common/form/MyInfoEditForm.jsx
src/components/common/form/MypageForm.jsx
src/components/common/layout/Header.jsx
src/components/document/DocsList.jsx
src/components/document/Document.jsx
src/components/mypage/MypageScrap.jsx
src/components/mypage/MypageScrapDetail.jsx
src/services/index.jsx
src/services/mypage.jsx
src/services/user.jsx

로그인 시 cors 해결 및 닉네임, 이메일 설정. 
근데 백엔드 수정 전이라 임시 값 넣어놓음

fix: 로그인 cors 해결

---

src/components/common/form/LoginForm.jsx
src/store/userReducer.js

fix:substract email

---

package-lock.json
package.json
src/components/admin/AdminBox.jsx
src/components/admin/EditInfo.jsx
src/components/admin/RequestContain.jsx
src/components/admin/RequestContainerBox.jsx
src/components/common/form/LoginForm.jsx
src/components/common/form/MyInfoEditForm.jsx
src/components/common/form/MypageForm.jsx
src/components/common/form/RegisterForm.jsx
src/components/common/layout/MypageSidebar.jsx
src/components/common/layout/Sidebar.jsx
src/components/common/layout/SidebarList.jsx
src/components/common/mypage/ScrapDocs.jsx
src/pages/BasicInfoEditReq.jsx
src/pages/NewDocsReq.jsx
src/services/index.jsx
src/store/index.js
src/store/sidebar.js

- 마이페이지 비밀번호 수정 부분 수정.
- 리액트 훅폼 사용하려고 설치했는데 사용 안했습니다... 그래도 혹시 모르니 한번 설치해주세요....
- 비밀번호 수정 완료했습니다. 모달창 아직 안 만들어서 프롬프트 창으로 이메일이랑 비밀번호 입력해야 수정할 수 있게 구현해놨습니다.
-사이드바 수정

fix:mypage-edit password edit

---

.github/workflows/deploy.yml
package-lock.json
package.json
pnpm-lock.yaml
src/components/common/layout/Header.jsx
src/components/common/layout/Map.jsx
src/components/common/layout/OtherMap.jsx
src/components/document/DocsList.jsx
src/components/document/DocumentInputGroup.jsx
src/store/index.js
src/store/store.js
vercel.json
vite.config.js

feat: 배포 및 미로그인시 상세문서 접근 불가

---

src/components/document/DocsList.jsx
src/components/search/SearchBar.jsx

release 브랜치 업데이트

---

src/components/document/Document.jsx
src/components/register/Question.jsx

fix: mardown, cursor

---

index.html
src/components/document/Document.jsx

fix: 편집시 마크다운 테마 변경

---

jsconfig.json
src/components/common/Input/SelectInput.jsx
src/components/common/button/ScrapBtn.jsx
src/components/common/button/ToggleBtn.jsx
src/components/createDocument/CreateDocument.jsx
src/components/createDocument/DocumentInput.jsx
src/components/createDocument/DocumentInputGroup.jsx
src/components/docsList/DocsItem.jsx
src/components/docsList/DocsList.jsx
src/components/document/Basic.jsx
src/components/document/Content.jsx
src/components/document/Document.jsx
src/components/document/DocumentHeading.jsx
src/components/document/DocumentLabel.jsx
src/components/document/DocumentTime.jsx
src/components/document/ErrorMsg.jsx
src/components/mypage/ScrapList.jsx
src/components/search/SearchBar.jsx
src/components/search/SearchItem.jsx
src/hooks/useHandleAddress.js
src/pages/DocumentPage.jsx
src/styles/DocsItem.jsx
src/styles/DocsList.jsx
src/styles/StyledInput.jsx
vite.config.js

-  전체적인 폰트 크기, 넓이 등을 키움
- 폰트 및 넓이 크기 키움: 문서 목록 조회, 문서 상세 조회 화면, 문서 생성 화면, 스크랩 조회 화면
- 도형 크기 키움: 스크랩 버튼, 토글 버튼
- 문서 접는 토글버튼 hover시 효과를 추가
- 겹치는 styled component 추출
비즈니스 로직은 아직 고치는 중이라서 css 위주로 봐주세요~!!
close #135

style: 폰트 크기, 넓이 등 스타일 변경

---

src/components/common/button/HeaderButtons.jsx

style: 메뉴 아이콘 커서 pointer로 변경

---

src/components/common/form/RegisterForm.jsx
src/utils/alert.js
src/utils/registerRules.js
vite.config.js

fix: 닉네임 길이 수정

---

src/components/common/Input/InputGroup.jsx

fix: 마이페이지 버튼 위치 수정

---

src/utils/toast.js

style: toast 위치 변경

---

src/components/document/Basic.jsx
src/components/document/Content.jsx
src/components/document/DocumentTime.jsx
src/components/search/SearchBar.jsx
src/components/search/SearchItem.jsx
src/hooks/useHandleClickOutside.js
src/index.css
src/services/index.jsx

**버그**
- 문서 편집을 하다가 검색을 했을 때, 검색 결과로 이동하지 못하는 문제를 수정
**리팩토링**
- 마크다운 시 글 목록(ul,li)이 적용 안되는 문제를 해결
- 예외 처리 구체화 (500, 403 에러일때 alert창 추가)
- 기본정보, 문서내용 편집 컴포넌트 리팩토링(커밋 내용을 참고하세요~~)
closes #151 #138

refactor: 검색 결과가 잘 이동하지 못하는 문제를 해결한다.

---

src/components/document/Content.jsx

- 문서 편집 시간을 반영했습니다.
closes #153

fix: 문서 편집 시간 반영

---

src/components/Map/MainMap.jsx
src/components/Map/MapWithClickEvent.jsx
src/components/common/button/Button.jsx
src/components/createDocument/CreateDocument.jsx
src/components/document/Basic.jsx
src/components/document/Content.jsx
src/components/document/DocumentHeading.jsx
src/hooks/useHandleAddress.js
src/pages/AddPost.jsx
src/pages/BasicInfoEditReq.jsx
src/pages/DocumentPage.jsx
src/pages/NewDocsReq.jsx

- 문서 생성 코드 리팩토링
- 문서 생성시 다루는 주소 커스텀훅 리팩토링
- 불필요한 useEffect 삭제
- backgroundColor 카멜케이스로 변경
- 지도에 isEdit prop추가
- 편집 가능상태일때만 지도 마커 추가 가능
- closes #169

refactor: 문서 생성 리팩토링

---

src/components/common/button/ScrapBtn.jsx
src/components/docsList/DocsItem.jsx
src/components/docsList/DocsList.jsx
src/components/document/Basic.jsx
src/components/mypage/MypageScrap.jsx
src/components/mypage/ScrapList.jsx
src/hooks/useScrap.js
src/pages/DocumentListPage.jsx

- 불필요한 스크랩 상태 관리 삭제
- 겹치는 로직 커스텀훅으로 분리
- closes #175

refactor: 스크랩 로직 수정

---

src/App.jsx
src/pages/NotFound.jsx
src/routes.js

feat: NotFound 페이지 구현

---

package-lock.json
package.json
src/components/document/Basic.jsx
src/components/document/Content.jsx
src/components/mypage/ScrapList.jsx
src/hooks/useWebSocket.js
src/services/stomp.js
vite.config.js

- 문서 편집(기본정보, 내용)시 웹소켓 적용
- stomp 객체 정의
- webSocket 커스텀훅 구현
- closes #164

feat: 문서 편집 시 웹소켓 적용

---

src/components/common/button/ToggleBtn.jsx

- 1023px이하일 때 토글버튼 위치 수정
- closes #178

fix: 토글버튼 위치 수정

---

index.html
package-lock.json
package.json
src/components/Map/MainMap.jsx
src/constant/document/auth.js
src/hooks/useWebSocket.js
src/index.css
src/services/stomp.js
src/utils/alert.js
src/utils/toast.js
vite.config.js

- 편집 상태일 때 웹소켓 연결
- 스크랩 안내문구 변경
- 모바일 사이즈에서 화면이 확대되지 않도록 설정
- map컴포넌트 높이 변경
- closes

fix: 자잘한 에러 수정

---

.github/workflows/deploy.yml

fix: cicd 브랜치 변경

---

src/components/map/MainMap.jsx
src/components/map/MapContainer.jsx
src/components/map/MapWithClickEvent.jsx
src/pages/AddPost.jsx
src/pages/DocumentPage.jsx

style: 대소문자 구분

---

src/components/common/input/Input.jsx
src/components/common/input/InputGroup.jsx
src/components/common/input/SelectInput.jsx

style: input 폴더 대소문자 구분

---

.github/workflows/deploy.yml
src/components/common/form/MyInfoEditForm.jsx

chore: permission 지정

---

.github/workflows/deploy.yml

- github_token 액세스 정의
- closes

chore: github_token 액세스 정의

---

.github/workflows/deploy.yml

chore: build 폴더 변경

---

src/pages/DocumentListPage.jsx

fix: 데이터 체이닝 적용

---

src/pages/DocumentListPage.jsx

fix: flatMap 에러 수정

---

.github/workflows/deploy.yml

chore: .env workflow에 추가

---

.github/workflows/deploy.yml

chore: 경로에 큰따옴표 추가
